### ISSUE TITLE
Adding links to the contact icons

### ISSUE THREAD

**Issue by tokyo3001** [Naman-sharma00100/Basic_website_HTML_CSS_only#23]
I can add links to the contact icons so that it can directly display the respected platform.

**Comment by tokyo3001** [comment]
@Naman-sharma00100 Can you assign me this issue under hacktoberfest2022?

**Comment by Naman-sharma00100** [comment]
Sure..! Remember to first pull the latest changes then work on new ones.

**Comment by sachin2709** [comment]
CAN I MAKE FOOTER BETTER @Naman-sharma00100
